server:
  port: 8761

eureka:
  server:
    peer-node-read-timeout-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:WannaBeIn3ureka@localhost:8761/eureka/


spring:
  security:
    user:
      name: user
      password: WannaBeIn3ureka